package ports

import (
	"context"
	"errors"
	"strings"
)

type claoOwnerKey struct{}

// WithCLAOOwner is an in-process scheduling capability, never an HTTP field.
// Ordinary sessions do not require it. The verifier shares its mission's owner.
func WithCLAOOwner(ctx context.Context, id string) context.Context {
	return context.WithValue(ctx, claoOwnerKey{}, id)
}

func RequireCLAOOwner(ctx context.Context, sessionOwner string) error {
	if sessionOwner == "" {
		return nil
	}
	if id, _ := ctx.Value(claoOwnerKey{}).(string); id != "" && CLAOMissionOwner(sessionOwner) == id {
		return nil
	}
	return errors.New("此 Session 由 CLAO 闭环控制；不能单独恢复、重试或切换执行配置")
}

// CLAOMissionOwner returns only the immutable mission portion. Mission IDs
// exclude colons; native role/replacement identities are generated by CLAO.
func CLAOMissionOwner(owner string) string { id, _, _ := strings.Cut(owner, ":"); return id }
func CLAOSemanticOwner(owner string) bool {
	_, tail, _ := strings.Cut(owner, ":")
	role, _, _ := strings.Cut(tail, ":")
	return role == "verifier" || role == "auditor" || role == "planner"
}
