// Package cursoracp binds the user's own Cursor Agent installation to AO's
// reusable ACP Chat transport.
package cursoracp

import (
	"context"
	"crypto/sha256"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"strings"

	acpsdk "github.com/coder/acp-go-sdk"

	acpdriver "github.com/aoagents/agent-orchestrator/backend/internal/adapters/chatdriver/acp"
	"github.com/aoagents/agent-orchestrator/backend/internal/adapters/chatdriver/nativeacp"
	"github.com/aoagents/agent-orchestrator/backend/internal/domain"
	"github.com/aoagents/agent-orchestrator/backend/internal/ports"
)

// New launches `cursor-agent acp` from the exact binary resolved by the
// existing Cursor adapter. Models and slash commands come from the live ACP
// session advertisements. Cursor owns tools, project rules, and auth; AO adds a
// session-scoped standing rule and resolves permissions through ACP.
func New(plugin nativeacp.Plugin, log *slog.Logger) ports.ChatDriver {
	return nativeacp.New(plugin, nativeacp.Config{
		Harness:          domain.HarnessCursor,
		Configure:        configure,
		SessionOptions:   sessionOptions,
		PermissionPolicy: permissionPolicy,
		ClientExtension:  handleExtension,
		ClientExtensionAliases: map[string]string{
			askQuestionMethod: "_cursor/ask_question",
			createPlanMethod:  "_cursor/create_plan",
		},
		ValidateTurnSettings: validateTurnSettings,
		VersionProbe:         versionProbe,
	}, log)
}

func validateTurnSettings(initial ports.PermissionMode, settings ports.ChatTurnSettings) error {
	if settings.Approval == "" {
		return nil
	}
	initial = ports.NormalizePermissionMode(initial)
	requested := ports.NormalizePermissionMode(settings.Approval)
	if initial == requested {
		return nil
	}
	if cursorProcessPermissionMode(initial) || cursorProcessPermissionMode(requested) {
		return fmt.Errorf(
			"cursor ACP permission mode change from %q to %q requires restarting Chat",
			initial, requested,
		)
	}
	return nil
}

func cursorProcessPermissionMode(mode ports.PermissionMode) bool {
	return mode == ports.PermissionModeAuto || mode == ports.PermissionModeBypassPermissions
}

func configure(ctx context.Context, cfg acpdriver.LaunchConfig) ([]string, map[string]string, error) {
	args := make([]string, 0, 4)
	switch ports.NormalizePermissionMode(cfg.Permissions) {
	case ports.PermissionModeAuto:
		args = append(args, "--auto-review")
	case ports.PermissionModeBypassPermissions:
		args = append(args, "--force")
	}
	if strings.TrimSpace(cfg.SystemPrompt) != "" {
		pluginDir, err := writeStandingRule(ctx, cfg)
		if err != nil {
			return nil, nil, err
		}
		args = append(args, "--plugin-dir", pluginDir)
	}
	args = append(args, "acp")
	return args, nil, nil
}

func writeStandingRule(ctx context.Context, cfg acpdriver.LaunchConfig) (string, error) {
	if err := ctx.Err(); err != nil {
		return "", err
	}
	if strings.TrimSpace(cfg.DataDir) == "" {
		return "", fmt.Errorf("cursor ACP standing instructions require AO data directory")
	}
	sessionKey := fmt.Sprintf("%x", sha256.Sum256([]byte(cfg.SessionID)))
	pluginDir := filepath.Join(cfg.DataDir, "cursor", "acp-plugins", sessionKey)
	manifestDir := filepath.Join(pluginDir, ".cursor-plugin")
	rulesDir := filepath.Join(pluginDir, "rules")
	if err := os.MkdirAll(manifestDir, 0o700); err != nil {
		return "", fmt.Errorf("create Cursor ACP plugin manifest directory: %w", err)
	}
	if err := ctx.Err(); err != nil {
		return "", err
	}
	if err := os.MkdirAll(rulesDir, 0o700); err != nil {
		return "", fmt.Errorf("create Cursor ACP plugin rules directory: %w", err)
	}
	if err := ctx.Err(); err != nil {
		return "", err
	}
	manifest := []byte(`{"name":"ao-standing-instructions","displayName":"Agent Orchestrator Standing Instructions","version":"1.0.0","description":"Session-scoped standing instructions generated by Agent Orchestrator","author":{"name":"Agent Orchestrator"}}`)
	if err := os.WriteFile(filepath.Join(manifestDir, "plugin.json"), manifest, 0o600); err != nil {
		return "", fmt.Errorf("write Cursor ACP plugin manifest: %w", err)
	}
	if err := ctx.Err(); err != nil {
		return "", err
	}
	rule := "---\ndescription: Agent Orchestrator standing instructions for this managed session\nalwaysApply: true\n---\n\n" + cfg.SystemPrompt + "\n"
	if err := os.WriteFile(filepath.Join(rulesDir, "ao-standing.mdc"), []byte(rule), 0o600); err != nil {
		return "", fmt.Errorf("write Cursor ACP standing rule: %w", err)
	}
	if err := ctx.Err(); err != nil {
		return "", err
	}
	return pluginDir, nil
}

func permissionPolicy(
	mode ports.PermissionMode,
	params acpsdk.RequestPermissionRequest,
) (acpsdk.PermissionOptionId, bool) {
	mode = ports.NormalizePermissionMode(mode)
	if mode == ports.PermissionModeAcceptEdits {
		kind := acpsdk.ToolKind("")
		if params.ToolCall.Kind != nil {
			kind = *params.ToolCall.Kind
		}
		if kind != acpsdk.ToolKindEdit && kind != acpsdk.ToolKindDelete && kind != acpsdk.ToolKindMove {
			return "", false
		}
		return permissionOption(params.Options, acpsdk.PermissionOptionKindAllowOnce)
	}
	if mode == ports.PermissionModeBypassPermissions {
		if id, ok := permissionOption(params.Options, acpsdk.PermissionOptionKindAllowAlways); ok {
			return id, true
		}
		return permissionOption(params.Options, acpsdk.PermissionOptionKindAllowOnce)
	}
	return "", false
}

func permissionOption(
	options []acpsdk.PermissionOption,
	kind acpsdk.PermissionOptionKind,
) (acpsdk.PermissionOptionId, bool) {
	for _, option := range options {
		if option.Kind == kind {
			return option.OptionId, true
		}
	}
	return "", false
}

func sessionOptions(settings ports.ChatTurnSettings) []acpdriver.SessionOption {
	if settings.Model == "" {
		return nil
	}
	return []acpdriver.SessionOption{{ID: "model", Value: settings.Model}}
}
