/* P01 actual Edge/Panel/WinCred + isolated protocol/HTTP process boundaries. */
const {chromium}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const [origin,project,out]=process.argv.slice(2);fs.mkdirSync(out,{recursive:true});
const fakeKey='p01-isolated-fake-credential-never-a-real-key';
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 const context=await browser.newContext({viewport:{width:1440,height:900}}),page=await context.newPage();
 const errors=[],writes=[];
 page.on('pageerror',e=>errors.push(e.message));
 // Retain only path and non-secret config requests in this test; never credentials.
 page.on('request',r=>{if(r.method()==='POST')writes.push({path:new URL(r.url()).pathname,...(r.url().endsWith('/api/mission')?{body:r.postDataJSON()}: {})});});
 await page.goto(origin);await page.waitForFunction(()=>LIVE?.default_config && PROJECTS.length);
 await page.locator('[data-view="models"]').first().click();
 await page.waitForFunction(()=>!!loadConnections.values);
 assert(!(await page.locator('#connectionList').textContent()).includes('真实角色准入待验证'));
 await page.locator('#connectionEditor > summary').click();
 await page.evaluate(()=>window.scrollTo(0,0));
 await page.selectOption('#profile_service','bigmodel_general');
 await page.fill('#profile_label','浏览器 GLM');await page.fill('#profile_key',fakeKey);
 await page.fill('#profile_model','glm-4.7');await page.locator('#profile_model').blur();
 await page.waitForFunction(()=>document.getElementById('saveProfile').dataset.blocked!=='1');
 await page.locator('#connectionEditor details summary').click();
 await page.fill('#profile_timeout_seconds','4.125');await page.selectOption('#profile_thinking','enabled');
 await page.locator('#saveProfile').evaluate(b=>{b.click();b.click();});
 await page.waitForFunction(()=>loadConnections.values?.model_profiles?.some(p=>p.label==='浏览器 GLM'));
 const identity=await page.evaluate(()=>loadConnections.values.model_profiles.at(-1).id);
 assert.equal(writes.filter(w=>w.path==='/api/model-connections').length,1);
 assert.equal(await page.inputValue('#profile_key'),'');
 assert(!(await page.content()).includes(fakeKey));
 assert(!(await page.evaluate(()=>JSON.stringify(localStorage))).includes(fakeKey));
 await page.selectOption('#default_profile_verifier',identity);await page.click('#saveBindings');
 await page.waitForFunction(id=>LIVE?.default_config?.values.roles.verifier.profile===id,identity);
 await page.locator('#connectionEditor > summary').click();
 await page.screenshot({path:path.join(out,'models-light.png'),fullPage:true});
 // No stale pre-confirmation defaults and no model request from settings.
 await page.reload();await page.waitForFunction(id=>LIVE?.default_config?.values.roles.verifier.profile===id,identity);
 await page.locator('[data-view="overview"]').first().click();await page.click('#btnNew');await page.selectOption('#f_project',project);
 await page.waitForFunction(()=>SOURCE?.project_id===document.getElementById('f_project').value);
 await page.click('#stepNext');await page.fill('#f_obj','配置与真实闭环 中文 <tag> "');await page.fill('#f_ac','x equals 2');
 await page.click('#stepNext');await page.fill('#f_paths','app.py');await page.fill('#f_gate',"python -c \"import runpy; assert runpy.run_path('app.py')['x'] == 2\"");
 await page.click('#stepNext');await page.waitForFunction(id=>FORM_CONFIG?.values.roles.verifier.profile===id,identity);
 assert((await page.locator('#formReview').textContent()).includes('glm-4.7'));
 assert((await page.locator('#formReview details pre').textContent()).includes('"thinking": "enabled"'));
 assert(await page.locator('#param_roles_verifier_model').isDisabled());
 await page.check('#sourceConfirmed');await page.click('#btnStart');
 assert.equal(writes.filter(w=>w.path==='/api/mission').length,0);
 assert((await page.locator('#externalConsentError').textContent()).includes('确认'));
 await page.screenshot({path:path.join(out,'task-consent.png'),fullPage:true});
 await page.check('#externalConsent');await page.click('#btnStart');
 await page.waitForFunction(()=>['MISSION_DONE','HUMAN','FAILED','CANCELLED'].includes(LIVE?.mission?.state) || document.getElementById('formSubmitError').textContent,{},{timeout:30000});
 assert.equal(await page.evaluate(()=>LIVE?.mission?.state),'MISSION_DONE',await page.evaluate(()=>JSON.stringify({reason:LIVE?.mission?.reason,errors:LIVE?.panel_errors,submit:document.getElementById('formSubmitError').textContent})));
 assert.equal(writes.filter(w=>w.path==='/api/mission').length,1);
 const sent=writes.find(w=>w.path==='/api/mission').body;
 assert.equal(sent.external_service_consent,'bigmodel_general');
 assert.equal(sent.config_snapshot.values.roles.verifier.profile,identity);
 assert.equal(await page.evaluate(()=>LIVE.mission_config.snapshot.values.model_profiles.at(-1).timeout_seconds),4.125);
 const facts=await page.evaluate(()=>LIVE.phases.roles.verifier);
 assert.equal(facts.provider,'bigmodel_general');assert.equal(facts.confirmed_model,'glm-4.7-resolved');assert.equal(facts.cost,null);
 assert(!(await page.evaluate(()=>JSON.stringify(LIVE))).includes(fakeKey));
 await page.locator('[data-view="models"]').first().click();
 await page.locator('#view-models > details.advanced > summary').click();
 assert((await page.locator('#modelStatus').textContent()).includes('bigmodel_general'));
 await page.evaluate(()=>applyTheme('dark'));await page.setViewportSize({width:390,height:844});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.evaluate(()=>window.scrollTo(0,0));
 await page.screenshot({path:path.join(out,'models-dark-390.png')});
 assert.deepEqual(errors,[]);await browser.close();console.log('P01 browser: profiles, OS credentials, freeze/consent, actual Controller/Gate + local HTTP Verifier, safe rendering PASS');
})().catch(e=>{console.error(e);process.exit(1);});
