"""Closed-loop Agent Orchestrator adapter."""

from .ao_client import (
    AOClient,
    AOClientError,
    AOConversationTimeoutError,
    AODiscoveryError,
    AORequestError,
    AOResponseError,
)
from .loop_runner import (
    GatedRunResult,
    LoopProtocolError,
    LoopRunError,
    LoopTimeoutError,
    ObservedLoopResult,
    RunResult,
    TurnFailedError,
    UnsafeSessionError,
    run_audited_once,
    run_gated_once,
    run_observed_loop,
    run_once,
)
from .integration_gate import (
    GateStepResult,
    IntegrationGateResult,
    run_integration_gate,
)
from .observer import (
    ActivityObservation,
    FailureOccurrence,
    MessageObservation,
    Observation,
    ObserverError,
    ObserverResult,
    ObserverTrigger,
    TurnObservation,
    WorkspaceFileObservation,
    capture_observation,
    evaluate_observation,
    normalize_failure_fingerprint,
)
from .protocol import AuditReport, AuditRequest, Decision, PlannerDecision

__all__ = [
    "AOClient",
    "AOClientError",
    "AOConversationTimeoutError",
    "AODiscoveryError",
    "AORequestError",
    "AOResponseError",
    "AuditReport",
    "AuditRequest",
    "ActivityObservation",
    "Decision",
    "FailureOccurrence",
    "GateStepResult",
    "GatedRunResult",
    "IntegrationGateResult",
    "LoopProtocolError",
    "LoopRunError",
    "LoopTimeoutError",
    "MessageObservation",
    "Observation",
    "ObservedLoopResult",
    "ObserverError",
    "ObserverResult",
    "ObserverTrigger",
    "PlannerDecision",
    "RunResult",
    "TurnFailedError",
    "TurnObservation",
    "UnsafeSessionError",
    "WorkspaceFileObservation",
    "capture_observation",
    "evaluate_observation",
    "normalize_failure_fingerprint",
    "run_audited_once",
    "run_gated_once",
    "run_integration_gate",
    "run_observed_loop",
    "run_once",
]
