import { COMPANY } from "@ao/shared/constants";

export interface ThemeListing {
	slug: string;
	name: string;
	type: "dark" | "light";
	author: string;
	submittedBy: string;
	description: string;
	addedOn: string;
	source: {
		label: string;
		href: string;
	};
	tags: string[];
	ui: {
		background: string;
		foreground: string;
		card: string;
		cardForeground: string;
		primary: string;
		accent: string;
		border: string;
		sidebar: string;
		sidebarForeground: string;
	};
	terminal: {
		background: string;
		foreground: string;
		cursor: string;
		red: string;
		green: string;
		yellow: string;
		blue: string;
		magenta: string;
		cyan: string;
	};
}

export const themeListings: ThemeListing[] = [
	{
		slug: "github-dark-colorblind",
		name: "GitHub Dark Colorblind",
		type: "dark",
		author: "GitHub (primer/github-vscode-theme)",
		submittedBy: "tkcel",
		description:
			"A GitHub-inspired dark theme adapted for Agent Orchestrator with strong blue, amber, and green contrast.",
		addedOn: "March 26, 2026",
		source: {
			label: "Download",
			href: "/marketplace/themes/github-dark-colorblind.json",
		},
		tags: ["GitHub", "Dark", "High contrast"],
		ui: {
			background: "#0d1117",
			foreground: "#e6edf3",
			card: "#161b22",
			cardForeground: "#e6edf3",
			primary: "#2f81f7",
			accent: "#1f6feb",
			border: "#30363d",
			sidebar: "#010409",
			sidebarForeground: "#e6edf3",
		},
		terminal: {
			background: "#0d1117",
			foreground: "#e6edf3",
			cursor: "#2f81f7",
			red: "#ff7b72",
			green: "#3fb950",
			yellow: "#d29922",
			blue: "#58a6ff",
			magenta: "#bc8cff",
			cyan: "#39c5cf",
		},
	},
	{
		slug: "catppuccin-mocha",
		name: "Catppuccin Mocha",
		type: "dark",
		author: "Catppuccin",
		submittedBy: "tamarazuk",
		description: "The Mocha variant from the Catppuccin theme PR for Agent Orchestrator.",
		addedOn: "March 21, 2026",
		source: {
			label: "Download",
			href: "/marketplace/themes/catppuccin-mocha.json",
		},
		tags: ["Catppuccin", "Dark"],
		ui: {
			background: "#1e1e2e",
			foreground: "#cdd6f4",
			card: "#181825",
			cardForeground: "#cdd6f4",
			primary: "#cba6f7",
			accent: "#45475a",
			border: "#45475a",
			sidebar: "#181825",
			sidebarForeground: "#cdd6f4",
		},
		terminal: {
			background: "#1e1e2e",
			foreground: "#cdd6f4",
			cursor: "#f5e0dc",
			red: "#f38ba8",
			green: "#a6e3a1",
			yellow: "#f9e2af",
			blue: "#89b4fa",
			magenta: "#f5c2e7",
			cyan: "#89dceb",
		},
	},
	{
		slug: "catppuccin-macchiato",
		name: "Catppuccin Macchiato",
		type: "dark",
		author: "Catppuccin",
		submittedBy: "tamarazuk",
		description:
			"The Macchiato variant from the Catppuccin theme PR for Agent Orchestrator.",
		addedOn: "March 21, 2026",
		source: {
			label: "Download",
			href: "/marketplace/themes/catppuccin-macchiato.json",
		},
		tags: ["Catppuccin", "Dark"],
		ui: {
			background: "#24273a",
			foreground: "#cad3f5",
			card: "#1e2030",
			cardForeground: "#cad3f5",
			primary: "#c6a0f6",
			accent: "#494d64",
			border: "#494d64",
			sidebar: "#1e2030",
			sidebarForeground: "#cad3f5",
		},
		terminal: {
			background: "#24273a",
			foreground: "#cad3f5",
			cursor: "#f4dbd6",
			red: "#ed8796",
			green: "#a6da95",
			yellow: "#eed49f",
			blue: "#8aadf4",
			magenta: "#f5bde6",
			cyan: "#91d7e3",
		},
	},
	{
		slug: "catppuccin-frappe",
		name: "Catppuccin Frappé",
		type: "dark",
		author: "Catppuccin",
		submittedBy: "tamarazuk",
		description:
			"The Frappé variant from the Catppuccin theme PR for Agent Orchestrator.",
		addedOn: "March 21, 2026",
		source: {
			label: "Download",
			href: "/marketplace/themes/catppuccin-frappe.json",
		},
		tags: ["Catppuccin", "Dark"],
		ui: {
			background: "#303446",
			foreground: "#c6d0f5",
			card: "#292c3c",
			cardForeground: "#c6d0f5",
			primary: "#ca9ee6",
			accent: "#51576d",
			border: "#51576d",
			sidebar: "#292c3c",
			sidebarForeground: "#c6d0f5",
		},
		terminal: {
			background: "#303446",
			foreground: "#c6d0f5",
			cursor: "#f2d5cf",
			red: "#e78284",
			green: "#a6d189",
			yellow: "#e5c890",
			blue: "#8caaee",
			magenta: "#f4b8e4",
			cyan: "#99d1db",
		},
	},
	{
		slug: "catppuccin-latte",
		name: "Catppuccin Latte",
		type: "light",
		author: "Catppuccin",
		submittedBy: "tamarazuk",
		description: "The Latte variant from the Catppuccin theme PR for Agent Orchestrator.",
		addedOn: "March 21, 2026",
		source: {
			label: "Download",
			href: "/marketplace/themes/catppuccin-latte.json",
		},
		tags: ["Catppuccin", "Light"],
		ui: {
			background: "#eff1f5",
			foreground: "#4c4f69",
			card: "#e6e9ef",
			cardForeground: "#4c4f69",
			primary: "#8839ef",
			accent: "#bcc0cc",
			border: "#bcc0cc",
			sidebar: "#e6e9ef",
			sidebarForeground: "#4c4f69",
		},
		terminal: {
			background: "#eff1f5",
			foreground: "#4c4f69",
			cursor: "#dc8a78",
			red: "#d20f39",
			green: "#40a02b",
			yellow: "#df8e1d",
			blue: "#1e66f5",
			magenta: "#ea76cb",
			cyan: "#04a5e5",
		},
	},
	{
		slug: "ember",
		name: "Ember",
		type: "dark",
		author: "Agent Orchestrator",
		submittedBy: "AviPeltz",
		description:
			"The standalone Ember theme introduced before its palette became the default Dark theme.",
		addedOn: "December 1, 2025",
		source: {
			label: "Download",
			href: "/marketplace/themes/ember.json",
		},
		tags: ["Agent Orchestrator", "Dark", "Warm"],
		ui: {
			background: "#151110",
			foreground: "#eae8e6",
			card: "#201E1C",
			cardForeground: "#eae8e6",
			primary: "#eae8e6",
			accent: "#2a2827",
			border: "#2a2827",
			sidebar: "#1a1716",
			sidebarForeground: "#eae8e6",
		},
		terminal: {
			background: "#151110",
			foreground: "#eae8e6",
			cursor: "#e07850",
			red: "#dc6b6b",
			green: "#7ec699",
			yellow: "#e5c07b",
			blue: "#61afef",
			magenta: "#c678dd",
			cyan: "#56b6c2",
		},
	},
	{
		slug: "monokai-classic",
		name: "Monokai Classic",
		type: "dark",
		author: "Wimer Hazenberg",
		submittedBy: "AviPeltz",
		description:
			"The Monokai palette from the original desktop themes PR, exported with an import-safe marketplace ID.",
		addedOn: "November 27, 2025",
		source: {
			label: "Download",
			href: "/marketplace/themes/monokai-classic.json",
		},
		tags: ["Monokai", "Dark"],
		ui: {
			background: "#272822",
			foreground: "#f8f8f2",
			card: "#3e3d32",
			cardForeground: "#f8f8f2",
			primary: "#a6e22e",
			accent: "#49483e",
			border: "#49483e",
			sidebar: "#1e1f1c",
			sidebarForeground: "#f8f8f2",
		},
		terminal: {
			background: "#272822",
			foreground: "#f8f8f2",
			cursor: "#f8f8f2",
			red: "#f92672",
			green: "#a6e22e",
			yellow: "#f4bf75",
			blue: "#66d9ef",
			magenta: "#ae81ff",
			cyan: "#a1efe4",
		},
	},
	{
		slug: "one-dark-pro",
		name: "One Dark Pro",
		type: "dark",
		author: "Atom",
		submittedBy: "AviPeltz",
		description:
			"The original One Dark Pro theme from the first desktop themes PR, preserved as an importable file.",
		addedOn: "November 27, 2025",
		source: {
			label: "Download",
			href: "/marketplace/themes/one-dark-pro.json",
		},
		tags: ["Atom", "Dark"],
		ui: {
			background: "#282c34",
			foreground: "#abb2bf",
			card: "#2c313c",
			cardForeground: "#abb2bf",
			primary: "#61afef",
			accent: "#3e4451",
			border: "#3e4451",
			sidebar: "#21252b",
			sidebarForeground: "#abb2bf",
		},
		terminal: {
			background: "#282c34",
			foreground: "#abb2bf",
			cursor: "#528bff",
			red: "#e06c75",
			green: "#98c379",
			yellow: "#e5c07b",
			blue: "#61afef",
			magenta: "#c678dd",
			cyan: "#56b6c2",
		},
	},
	{
		slug: "atlas",
		name: "Atlas",
		type: "light",
		author: "Baris Can Sayin",
		submittedBy: "itsbariscan",
		description:
			"An old map atlas opened on a library table. Faded teal water, dust-rose place names, mountain-shadow brown on parchment.",
		addedOn: "May 7, 2026",
		source: {
			label: "Download",
			href: "/marketplace/themes/atlas.json",
		},
		tags: ["Light", "Cartographic"],
		ui: {
			background: "#ebe2cb",
			foreground: "#2a2620",
			card: "#e0d6bb",
			cardForeground: "#2a2620",
			primary: "#3e7a78",
			accent: "#c8bd96",
			border: "#b3a684",
			sidebar: "#e6dcc1",
			sidebarForeground: "#2a2620",
		},
		terminal: {
			background: "#ebe2cb",
			foreground: "#2a2620",
			cursor: "#3e7a78",
			red: "#a8473a",
			green: "#5b773d",
			yellow: "#c89e4f",
			blue: "#3e7a78",
			magenta: "#6e5294",
			cyan: "#5d8a85",
		},
	},
	{
		slug: "brutalist",
		name: "Brutalist",
		type: "dark",
		author: "Baris Can Sayin",
		submittedBy: "itsbariscan",
		description:
			"Concrete-and-glass discipline. Black, white, three greys. One color, used once. The architectural equivalent of a Bauhaus chair.",
		addedOn: "May 7, 2026",
		source: {
			label: "Download",
			href: "/marketplace/themes/brutalist.json",
		},
		tags: ["Dark", "Minimal", "High contrast"],
		ui: {
			background: "#0a0a0a",
			foreground: "#e8e8e8",
			card: "#181818",
			cardForeground: "#e8e8e8",
			primary: "#ff3300",
			accent: "#2e2e2e",
			border: "#2e2e2e",
			sidebar: "#080808",
			sidebarForeground: "#bdbdbd",
		},
		terminal: {
			background: "#0a0a0a",
			foreground: "#e8e8e8",
			cursor: "#ff3300",
			red: "#ff3300",
			green: "#bdbdbd",
			yellow: "#e8e8e8",
			blue: "#7a7a7a",
			magenta: "#bdbdbd",
			cyan: "#9c9c9c",
		},
	},
	{
		slug: "console",
		name: "Console",
		type: "dark",
		author: "Baris Can Sayin",
		submittedBy: "itsbariscan",
		description:
			"Phosphor green on a void that leans green, not blue. A 1980s P1-phosphor CRT, after midnight.",
		addedOn: "May 7, 2026",
		source: {
			label: "Download",
			href: "/marketplace/themes/console.json",
		},
		tags: ["Dark", "Retro", "CRT"],
		ui: {
			background: "#050a05",
			foreground: "#2ed85a",
			card: "#0a1308",
			cardForeground: "#2ed85a",
			primary: "#2ed85a",
			accent: "#102510",
			border: "#0e2010",
			sidebar: "#020602",
			sidebarForeground: "#1a8c40",
		},
		terminal: {
			background: "#050a05",
			foreground: "#2ed85a",
			cursor: "#5dff8a",
			red: "#ff4040",
			green: "#2ed85a",
			yellow: "#f5d04b",
			blue: "#1a8c40",
			magenta: "#9affae",
			cyan: "#5dff8a",
		},
	},
	{
		slug: "ferro",
		name: "Ferro",
		type: "dark",
		author: "Baris Can Sayin",
		submittedBy: "itsbariscan",
		description:
			"A blacksmith's forge at first light. Cold dark steel meets hot orange embers. The metal hasn't lost its memory of fire.",
		addedOn: "May 7, 2026",
		source: {
			label: "Download",
			href: "/marketplace/themes/ferro.json",
		},
		tags: ["Dark", "Warm"],
		ui: {
			background: "#15181c",
			foreground: "#dcd4c8",
			card: "#1d2127",
			cardForeground: "#dcd4c8",
			primary: "#e85d1e",
			accent: "#3a3d44",
			border: "#3a3d44",
			sidebar: "#0c0d10",
			sidebarForeground: "#bdb4a4",
		},
		terminal: {
			background: "#15181c",
			foreground: "#dcd4c8",
			cursor: "#e85d1e",
			red: "#c63a1c",
			green: "#83a85c",
			yellow: "#f5b042",
			blue: "#5a8b9b",
			magenta: "#a85a3a",
			cyan: "#7ea3a8",
		},
	},
	{
		slug: "hangar",
		name: "Hangar",
		type: "dark",
		author: "Baris Can Sayin",
		submittedBy: "itsbariscan",
		description:
			"Working warehouse at end of shift: concrete grey, safety orange, diesel yellow, exit-sign red. Functional, not decorative.",
		addedOn: "May 7, 2026",
		source: {
			label: "Download",
			href: "/marketplace/themes/hangar.json",
		},
		tags: ["Dark", "Industrial"],
		ui: {
			background: "#1c1d1f",
			foreground: "#e8e6df",
			card: "#26282b",
			cardForeground: "#e8e6df",
			primary: "#ff6b1a",
			accent: "#3a3d42",
			border: "#3a3d42",
			sidebar: "#16171a",
			sidebarForeground: "#cfcec5",
		},
		terminal: {
			background: "#1c1d1f",
			foreground: "#e8e6df",
			cursor: "#ff6b1a",
			red: "#d62828",
			green: "#9aa066",
			yellow: "#e6c34c",
			blue: "#5c8b9b",
			magenta: "#a85a3a",
			cyan: "#7ea3a8",
		},
	},
	{
		slug: "inkwell",
		name: "Inkwell",
		type: "light",
		author: "Baris Can Sayin",
		submittedBy: "itsbariscan",
		description:
			"Fountain-pen blue ink on bone-white paper. A long-form essayist's draft surface: patient, literary, cool.",
		addedOn: "May 7, 2026",
		source: {
			label: "Download",
			href: "/marketplace/themes/inkwell.json",
		},
		tags: ["Light", "Paper"],
		ui: {
			background: "#f7f3eb",
			foreground: "#1c2840",
			card: "#ede8db",
			cardForeground: "#1c2840",
			primary: "#2c4a8a",
			accent: "#d9d2ba",
			border: "#d4cdb8",
			sidebar: "#f0ebde",
			sidebarForeground: "#1c2840",
		},
		terminal: {
			background: "#f7f3eb",
			foreground: "#1c2840",
			cursor: "#2c4a8a",
			red: "#9c3a3a",
			green: "#566b3e",
			yellow: "#cda85c",
			blue: "#2c4a8a",
			magenta: "#5b3e6b",
			cyan: "#3e6b78",
		},
	},
	{
		slug: "kintsugi",
		name: "Kintsugi",
		type: "dark",
		author: "Baris Can Sayin",
		submittedBy: "itsbariscan",
		description:
			"Black lacquer mended with gold dust. Cracks showing where the break was. The repair is the point, not what to hide.",
		addedOn: "May 7, 2026",
		source: {
			label: "Download",
			href: "/marketplace/themes/kintsugi.json",
		},
		tags: ["Dark", "Warm"],
		ui: {
			background: "#0d0a08",
			foreground: "#e6dac8",
			card: "#1a1612",
			cardForeground: "#e6dac8",
			primary: "#d4a04a",
			accent: "#2a221a",
			border: "#2a221a",
			sidebar: "#070504",
			sidebarForeground: "#bfb39c",
		},
		terminal: {
			background: "#0d0a08",
			foreground: "#e6dac8",
			cursor: "#d4a04a",
			red: "#c14747",
			green: "#9c9468",
			yellow: "#d4a04a",
			blue: "#5b8a85",
			magenta: "#a07a4a",
			cyan: "#7ea69c",
		},
	},
	{
		slug: "reactor",
		name: "Reactor",
		type: "dark",
		author: "Baris Can Sayin",
		submittedBy: "itsbariscan",
		description:
			"A cooling pool inside a research reactor: Cherenkov-blue glow on graphite walls, uranium-yellow caution.",
		addedOn: "May 7, 2026",
		source: {
			label: "Download",
			href: "/marketplace/themes/reactor.json",
		},
		tags: ["Dark", "Cool"],
		ui: {
			background: "#0d1216",
			foreground: "#cce6f5",
			card: "#141b22",
			cardForeground: "#cce6f5",
			primary: "#2cb4e8",
			accent: "#26323a",
			border: "#26323a",
			sidebar: "#070b0e",
			sidebarForeground: "#a3bcd1",
		},
		terminal: {
			background: "#0d1216",
			foreground: "#cce6f5",
			cursor: "#2cb4e8",
			red: "#e8412f",
			green: "#5da9b5",
			yellow: "#e8c635",
			blue: "#2cb4e8",
			magenta: "#9870b5",
			cyan: "#5dc8d8",
		},
	},
	{
		slug: "riso",
		name: "Riso",
		type: "light",
		author: "Baris Can Sayin",
		submittedBy: "itsbariscan",
		description:
			"Risograph print on cream paper. Fluorescent pink, soybean yellow, federal blue. Slightly off-register, slightly handmade.",
		addedOn: "May 7, 2026",
		source: {
			label: "Download",
			href: "/marketplace/themes/riso.json",
		},
		tags: ["Light", "Print"],
		ui: {
			background: "#f4ecd6",
			foreground: "#1a1812",
			card: "#ebe2c4",
			cardForeground: "#1a1812",
			primary: "#ff5290",
			accent: "#dccba0",
			border: "#d8c8a0",
			sidebar: "#efe7ce",
			sidebarForeground: "#1a1812",
		},
		terminal: {
			background: "#f4ecd6",
			foreground: "#1a1812",
			cursor: "#ff5290",
			red: "#c3263a",
			green: "#5f8a6a",
			yellow: "#c89a25",
			blue: "#1f4f8a",
			magenta: "#ff5290",
			cyan: "#5d8a98",
		},
	},
	{
		slug: "supernova",
		name: "Supernova",
		type: "dark",
		author: "Baris Can Sayin",
		submittedBy: "itsbariscan",
		description:
			"Hubble narrowband: deep-space black with nebula magentas, OIII teal, sulfur orange, ionized-hydrogen pink. Astronomical, not Photoshop space.",
		addedOn: "May 7, 2026",
		source: {
			label: "Download",
			href: "/marketplace/themes/supernova.json",
		},
		tags: ["Dark", "Space"],
		ui: {
			background: "#040712",
			foreground: "#dee5f5",
			card: "#0c1023",
			cardForeground: "#dee5f5",
			primary: "#d24aff",
			accent: "#1a2040",
			border: "#1a2040",
			sidebar: "#020410",
			sidebarForeground: "#a8b4d4",
		},
		terminal: {
			background: "#040712",
			foreground: "#dee5f5",
			cursor: "#d24aff",
			red: "#ff4477",
			green: "#7fcfa4",
			yellow: "#ffa040",
			blue: "#3fcfd8",
			magenta: "#d24aff",
			cyan: "#5dcfe6",
		},
	},
	{
		slug: "twilight-run",
		name: "Twilight Run",
		type: "dark",
		author: "Baris Can Sayin",
		submittedBy: "itsbariscan",
		description:
			"After the streetlights, before full night. Pre-dawn navy meets sodium-vapor orange, a single moment captured.",
		addedOn: "May 7, 2026",
		source: {
			label: "Download",
			href: "/marketplace/themes/twilight-run.json",
		},
		tags: ["Dark", "Warm"],
		ui: {
			background: "#0e1b2a",
			foreground: "#dde3ee",
			card: "#1c2638",
			cardForeground: "#dde3ee",
			primary: "#ff8a3d",
			accent: "#2e3a4e",
			border: "#2e3a4e",
			sidebar: "#0a1320",
			sidebarForeground: "#bbc4d4",
		},
		terminal: {
			background: "#0e1b2a",
			foreground: "#dde3ee",
			cursor: "#ff8a3d",
			red: "#e8526a",
			green: "#85b86a",
			yellow: "#f5e493",
			blue: "#5b9ec4",
			magenta: "#a07cd4",
			cyan: "#7ec4d4",
		},
	},
	{
		slug: "vellum",
		name: "Vellum",
		type: "light",
		author: "Baris Can Sayin",
		submittedBy: "itsbariscan",
		description:
			"Cream paper, deep ink, sepia accent. A typography-first light theme that prints as well as it screens.",
		addedOn: "May 7, 2026",
		source: {
			label: "Download",
			href: "/marketplace/themes/vellum.json",
		},
		tags: ["Light", "Paper"],
		ui: {
			background: "#f5efdc",
			foreground: "#1a1814",
			card: "#ede5cc",
			cardForeground: "#1a1814",
			primary: "#8b3a1a",
			accent: "#dccea7",
			border: "#c8b896",
			sidebar: "#efe7d0",
			sidebarForeground: "#1a1814",
		},
		terminal: {
			background: "#f5efdc",
			foreground: "#1a1814",
			cursor: "#8b3a1a",
			red: "#a82e2e",
			green: "#5e6b3a",
			yellow: "#a8862a",
			blue: "#4d6b6b",
			magenta: "#5b3e6b",
			cyan: "#5d7a78",
		},
	},
	{
		slug: "dracula",
		name: "Dracula",
		type: "dark",
		author: "Zeno Rocha",
		submittedBy: "itsbariscan",
		description:
			"A faithful port of Dracula: the dark theme with cyan, green, orange, pink, purple, red, yellow on deep slate.",
		addedOn: "May 7, 2026",
		source: {
			label: "Download",
			href: "/marketplace/themes/dracula.json",
		},
		tags: ["Dracula", "Dark"],
		ui: {
			background: "#282a36",
			foreground: "#f8f8f2",
			card: "#21222c",
			cardForeground: "#f8f8f2",
			primary: "#bd93f9",
			accent: "#44475a",
			border: "#44475a",
			sidebar: "#21222c",
			sidebarForeground: "#f8f8f2",
		},
		terminal: {
			background: "#282a36",
			foreground: "#f8f8f2",
			cursor: "#f8f8f2",
			red: "#ff5555",
			green: "#50fa7b",
			yellow: "#f1fa8c",
			blue: "#bd93f9",
			magenta: "#ff79c6",
			cyan: "#8be9fd",
		},
	},
	{
		slug: "gruvbox-dark",
		name: "Gruvbox Dark",
		type: "dark",
		author: "Pavel Pertsev",
		submittedBy: "itsbariscan",
		description:
			"Retro groove from Pavel Pertsev: warm dark base, ochre/olive/clay accents. Honest, woodgrain feel.",
		addedOn: "May 7, 2026",
		source: {
			label: "Download",
			href: "/marketplace/themes/gruvbox-dark.json",
		},
		tags: ["Gruvbox", "Dark"],
		ui: {
			background: "#282828",
			foreground: "#ebdbb2",
			card: "#1d2021",
			cardForeground: "#ebdbb2",
			primary: "#fabd2f",
			accent: "#504945",
			border: "#504945",
			sidebar: "#1d2021",
			sidebarForeground: "#d5c4a1",
		},
		terminal: {
			background: "#282828",
			foreground: "#ebdbb2",
			cursor: "#ebdbb2",
			red: "#cc241d",
			green: "#98971a",
			yellow: "#d79921",
			blue: "#458588",
			magenta: "#b16286",
			cyan: "#689d6a",
		},
	},
	{
		slug: "nord",
		name: "Nord",
		type: "dark",
		author: "Arctic Ice Studio",
		submittedBy: "itsbariscan",
		description:
			"An arctic, north-bluish color palette. Polar Night base, Snow Storm foreground, Frost primaries, Aurora accents.",
		addedOn: "May 7, 2026",
		source: {
			label: "Download",
			href: "/marketplace/themes/nord.json",
		},
		tags: ["Nord", "Dark"],
		ui: {
			background: "#2e3440",
			foreground: "#d8dee9",
			card: "#3b4252",
			cardForeground: "#eceff4",
			primary: "#88c0d0",
			accent: "#4c566a",
			border: "#4c566a",
			sidebar: "#272b35",
			sidebarForeground: "#d8dee9",
		},
		terminal: {
			background: "#2e3440",
			foreground: "#d8dee9",
			cursor: "#d8dee9",
			red: "#bf616a",
			green: "#a3be8c",
			yellow: "#ebcb8b",
			blue: "#81a1c1",
			magenta: "#b48ead",
			cyan: "#88c0d0",
		},
	},
	{
		slug: "rose-pine",
		name: "Rosé Pine",
		type: "dark",
		author: "Rosé Pine team",
		submittedBy: "itsbariscan",
		description:
			"All natural pine, faux fur and a bit of soho vibes for the classy minimalist. The original 'Main' variant.",
		addedOn: "May 7, 2026",
		source: {
			label: "Download",
			href: "/marketplace/themes/rose-pine.json",
		},
		tags: ["Rosé Pine", "Dark"],
		ui: {
			background: "#191724",
			foreground: "#e0def4",
			card: "#1f1d2e",
			cardForeground: "#e0def4",
			primary: "#c4a7e7",
			accent: "#403d52",
			border: "#403d52",
			sidebar: "#16141f",
			sidebarForeground: "#e0def4",
		},
		terminal: {
			background: "#191724",
			foreground: "#e0def4",
			cursor: "#e0def4",
			red: "#eb6f92",
			green: "#31748f",
			yellow: "#f6c177",
			blue: "#9ccfd8",
			magenta: "#c4a7e7",
			cyan: "#ebbcba",
		},
	},
	{
		slug: "solarized-dark",
		name: "Solarized Dark",
		type: "dark",
		author: "Ethan Schoonover",
		submittedBy: "itsbariscan",
		description:
			"Precision colors engineered for legibility, dark variant. Same accents as Solarized Light; only base tones flip.",
		addedOn: "May 7, 2026",
		source: {
			label: "Download",
			href: "/marketplace/themes/solarized-dark.json",
		},
		tags: ["Solarized", "Dark"],
		ui: {
			background: "#002b36",
			foreground: "#93a1a1",
			card: "#073642",
			cardForeground: "#eee8d5",
			primary: "#268bd2",
			accent: "#073642",
			border: "#073642",
			sidebar: "#001f27",
			sidebarForeground: "#93a1a1",
		},
		terminal: {
			background: "#002b36",
			foreground: "#839496",
			cursor: "#93a1a1",
			red: "#dc322f",
			green: "#859900",
			yellow: "#b58900",
			blue: "#268bd2",
			magenta: "#d33682",
			cyan: "#2aa198",
		},
	},
	{
		slug: "solarized-light",
		name: "Solarized Light",
		type: "light",
		author: "Ethan Schoonover",
		submittedBy: "itsbariscan",
		description:
			"Precision colors engineered for legibility, light variant. Cream paper base, ink foreground, same accent hues as Solarized Dark.",
		addedOn: "May 7, 2026",
		source: {
			label: "Download",
			href: "/marketplace/themes/solarized-light.json",
		},
		tags: ["Solarized", "Light"],
		ui: {
			background: "#fdf6e3",
			foreground: "#586e75",
			card: "#eee8d5",
			cardForeground: "#073642",
			primary: "#268bd2",
			accent: "#eee8d5",
			border: "#eee8d5",
			sidebar: "#f5eecb",
			sidebarForeground: "#657b83",
		},
		terminal: {
			background: "#fdf6e3",
			foreground: "#657b83",
			cursor: "#586e75",
			red: "#dc322f",
			green: "#859900",
			yellow: "#b58900",
			blue: "#268bd2",
			magenta: "#d33682",
			cyan: "#2aa198",
		},
	},
	{
		slug: "tokyo-night",
		name: "Tokyo Night",
		type: "dark",
		author: "Enkia",
		submittedBy: "itsbariscan",
		description:
			"A dark theme inspired by Tokyo at night: neon over deep navy, with cyan, magenta, and lavender highlights.",
		addedOn: "May 7, 2026",
		source: {
			label: "Download",
			href: "/marketplace/themes/tokyo-night.json",
		},
		tags: ["Tokyo Night", "Dark"],
		ui: {
			background: "#1a1b26",
			foreground: "#c0caf5",
			card: "#16161e",
			cardForeground: "#c0caf5",
			primary: "#7aa2f7",
			accent: "#292e42",
			border: "#292e42",
			sidebar: "#13141d",
			sidebarForeground: "#a9b1d6",
		},
		terminal: {
			background: "#1a1b26",
			foreground: "#c0caf5",
			cursor: "#c0caf5",
			red: "#f7768e",
			green: "#9ece6a",
			yellow: "#e0af68",
			blue: "#7aa2f7",
			magenta: "#bb9af7",
			cyan: "#7dcfff",
		},
	},
];

function buildIssueUrl(title: string) {
	return `${COMPANY.REPORT_ISSUE_URL}?title=${encodeURIComponent(title)}`;
}

export const marketplaceSubmissionLinks = {
	theme: buildIssueUrl("[Marketplace] Theme submission"),
	agent: buildIssueUrl("[Marketplace] Agent config submission"),
};

export function getAllThemeSlugs(): string[] {
	return themeListings.map((theme) => theme.slug);
}

export function getThemeListing(slug: string): ThemeListing | undefined {
	return themeListings.find((theme) => theme.slug === slug);
}
